blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a Question
    url: https://github.com/NiklasDerEchte/fresh-fetch/discussions
    about: Use GitHub Discussions for general questions or help.